logging:
  level:
    org.springframework: TRACE
server:
  port: 8888
spring:
  security:
    user:
      name: root
      password: password
  cloud:
    refresh:
      enabled: false
    config:
      server:
        git:
          cloneOnStart: false
          uri: https://github.com/luidoc/spring-cloud-config-repo.git
          repos:
            apps:
              uri: https://github.com/luidoc/spring-cloud-config-repo.git
              pattern:
                - '*/dev'
              search-paths:
                - '*/dev/config'
              defaultLabel: main
              timeout: 2                # Seconds server will wait to acquire an HTTP connection
              force-pull: false         # Force pull from the remote repository if the local copy is dirty
              skip-ssl-validation: true # Git server’s SSL certificate can be disabled
              try-master-branch: false
encrypt:
  key: asdfajazdf444jalasdfasdf
